<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Register</title>
</head>
<body>
    <div class="container">
        <div class="m-3 p-2 text-primary">
            <h2>Register</h2>
        </div>
        <div class="m-3 p-3">
            <?php echo $this->tag->form("");?>
            <?php
                echo "<label for='user_name'>Name</label>".$this->tag->textField(
                    [
                        'user_name', 
                        'class' => 'form-control', 
                        'placeholder' => 'Name'
                    ]
                );
            
                echo "<label for='user_email'>Email</label>".$this->tag->textField(
                    [
                        'user_email', 
                        'class' => 'form-control', 
                        'placeholder' => 'E-mail'
                    ]
                );
            
                echo "<label for='user_password'>Password</label>".$this->tag->textField(
                    [
                        'user_password', 
                        'class' => 'form-control', 
                        'placeholder' => 'Password'
                    ]
                );
            
                // echo "<label for='user_role'>Role</label>".$this->tag->select(
                //     [
                //         'user_role',
                //         $role,
                //         'using' => [
                //             'role_name', 
                //             'role_name',
                //         ],
                //         'useEmpty'   => false,
                //         'class' => 'form-control',
                //     ]
                // );
            
                echo $this->tag->submitButton(
                    [
                        'Register', 
                        'class' => 'form-control mt-3 btn-primary',
                        'name' => 'action'
                    ]
                );

                echo '<br>'.$this->tag->linkTo(
                    [
                        'register',
                        'Login Here!',
                        'class' => 'm-2 p-2 btn-primary rounded',
                    ]
                );
                echo '<br>';

                if (isset($success) && ($success == 1 || $success == 0)) {
                    $success = $success === true ? "success":"danger";
                    echo '<div class="alert alert-'.$success.'">';
                        echo $message;
                    echo '</div>';
                }
            ?>
            </form>

        </div>
    </div>
</body>
</html>