<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Product</title>
    <!-- <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> -->
</head>
<body>
    <div class="container">
        <div class="m-3 p-2 text-primary">
            <h2>Add Product</h2>
        </div>
        <div class="m-3 p-3">
            <?php echo $this->tag->form("product/add?bearer=".$this->request->getQuery('bearer'));?>
            <?php
                echo "<label for='product_name'>Name</label>".$this->tag->textField(
                    [
                        'product_name', 
                        'class' => 'form-control', 
                        'placeholder' => 'Name'
                    ]
                );
            ?>
            <?php
                echo "<label for='product_description'>Description</label>".$this->tag->textArea(
                    [
                        'product_description', 
                        'class' => 'form-control', 
                        'placeholder' => 'Description'
                    ]
                );
            ?>
            <?php
                echo "<label for='product_tags'>Tags</label>".$this->tag->textField(
                    [
                        'product_tags', 
                        'class' => 'form-control', 
                        'placeholder' => 'Tags'
                    ]
                );
            ?>
            <?php
                echo "<label for='product_price'>Price</label>".$this->tag->textField(
                    [
                        'product_price', 
                        'class' => 'form-control', 
                        'placeholder' => 'Price'
                    ]
                );
            ?>
            <?php
                echo "<label for='product_stock'>Stock</label>".$this->tag->textField(
                    [
                        'product_stock', 
                        'class' => 'form-control', 
                        'placeholder' => 'Stock'
                    ]
                );
            ?>
            <?php
                echo $this->tag->submitButton(
                    [
                        'Add Product', 
                        'class' => 'form-control mt-3 btn-primary',
                        'name' => 'action'
                    ]
                );
            ?>
            </form>
        </div>
    </div>
</body>
</html>