<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>

<body>
    <div class="container-fluid">
        <div class="container m-2 p-2">
            <div class="container">
                <h1 class="text text-primary fw fw-bold">Products</h1>
                <?php echo $this->tag->linkTo(
                    [
                        'product/add',
                        'Add Product',
                        'class' => 'btn btn-primary mb-2',
                    ]
                );
                ?>
                <input type='text' name='search' placeholder='Search' id='search' class='form-control'>
                <br>
            </div>
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Category</th>
                            <th scope="col">Price</th>
                            <th scope="col">Stock</th>
                            <th scope="col">Delete</th>
                            <th scope="col">Update</th>
                            <th scope="col">Glance</th>
                        </tr>            
                    </thead>
                    <tbody id='tbody'>
                        <?php
                        if (isset($content)) {
                            echo $content;
                        }
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="modal" id="popupview" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            </div>
        </div>
    </div>
</body>

</html>