<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User List</title>
</head>
<body>
    <div class="container-fluid">
        <div class="container m-2 p-2">
            <div class="container">
                <h1 class="text text-primary fw fw-bold">Users</h1>
                <?=$this->tag->linkTo(
                        [
                            'user/add?role='.$this->request->getQuery('bearer'),
                            'Add User',
                            'class' => 'btn btn-primary mb-2',
                        ]
                    );
                ?>
            </div>
            <div class="table-responsive">
                <table class="table table-sm">
                <thead>
                    <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Password</th>
                    <th scope="col">Role</th>
                    <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    echo $content;
                    ?>
                </tbody>
                </table>
            </div>
        </div>
    </div>
</body>
</html>