<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Order</title>
    <!-- <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> -->
</head>
<body>
    <div class="container">
        <div class="m-3 p-2 text-primary">
            <h2>Add Order</h2>
        </div>
        <div class="m-3 p-3">
        <?php echo $this->tag->form("order/add");?>
            <div id="fieldsDiv">
                <?php
                    echo "<label for='customer_name'>Customer Name</label>".$this->tag->textField(
                        [
                            'customer_name',
                            'class' => 'form-control',
                            'placeholder' => 'Name',
                            'required' => 'required'
                        ]
                    );
                ?>
                <?php
                echo "
                <label for='product_id'>Category</label>
                <select name='product_id' id='product_id_order' class='form-control' required>";
                foreach ($product as $value) {
                    echo "<option value='".$value['product_id']."'>".$value['product_name']."</option>";
                }
                echo "</select>";
                ?>
                <?php
                    echo "<label for='product_quantity'>Quantity</label>".$this->tag->textField(
                        [
                            'product_quantity',
                            'class' => 'form-control',
                            'placeholder' => 'Quantity',
                            'required' => 'required'
                        ]
                    );
                ?>
            </div>
            
            <!-- Variation DIV Start -->
            <div id="variantsOrderDiv">
                
            </div>
            <!-- Variation DIV End -->
            
            <div id="Orderprice">
            <?php
                    echo "<label for='product_price'>Price</label>".$this->tag->textField(
                        [
                            'product_price',
                            'class' => 'form-control',
                            'readonly' => 'readonly'
                        ]
                    );
                ?>
            </div>
            <?php
                echo $this->tag->submitButton(
                    [
                        'Add Order',
                        'class' => 'form-control mt-3 btn-primary',
                        'name' => 'action'
                    ]
                );
            ?>
            </form>
        </div>
    </div>
</body>
</html>