<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order List</title>
</head>

<body>
    <div class="container-fluid">
        <div class="container m-2 p-2">
            <div class="container">
                <h1 class="text text-primary fw fw-bold">Orders</h1>
                <?php echo $this->tag->linkTo(
                    [
                        'order/add',
                        'Add Order',
                        'class' => 'btn btn-primary mb-2',
                    ]
                );
                ?>
                <?php echo $this->tag->form('');?>
                <select name='filterDate' id='filterDate' class='form-control'>
                    <option>Today</option>
                    <option>This Week</option>
                    <option value="first day of this month">This Month</option>
                    <option>Custom</option>
                </select>
                <br>
                <select name="filterStatus" id="filterStatus" class="form-control">
                    <option>All</option>
                    <option>Paid</option>
                    <option>Processing</option>
                    <option>Dispatched</option>
                    <option>Shipped</option>
                    <option>Refunded</option>
                </select>
                <br>
                <button class="btn btn-primary">Apply Filters</button>
                <br>
                <div id="customDateField"></div><br>
                </form>
            </div>
            <div class="table-responsive">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Variant</th>
                            <th scope="col">Date</th>
                            <th scope="col">Status</th>
                            <th scope="col">Update Status</th>
                            <th scope="col">Delete</th>
                            <th scope="col">Glance</th>
                        </tr>            
                    </thead>
                    <tbody id='tbody'>
                        <?php
                        if (isset($content)) {
                            echo $content;
                        }
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="modal" id="popupview" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            </div>
        </div>
    </div>
</body>

</html>